export default [
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/10527',
    'label': 'Ukonmäki',
    'typeLabel': 'Kalliomaa',
    'broaderAreaLabel': 'Alahärmä',
    'source': 'DNA',
    'lat': '63.255930986944996',
    'long': '22.931255119909',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Pitkänen, Hillevi',
    'collectionYear': '1954'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/14530',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Alajärvi',
    'source': 'DNA',
    'lat': '62.938760120906',
    'long': '23.83670831702',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hanhisalo, Ritva',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/19989',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Alajärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Salo, Eeva-Kaisa',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/19990',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Alajärvi',
    'source': 'DNA',
    'lat': '62.938032764407',
    'long': '23.84020504084',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Taittonen, Reijo',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2318379',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lampinen-Käki, Alma',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53561',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1954'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53562',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53563',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1954'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53564',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53565',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53566',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53567',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53568',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1955'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53569',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1955'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53570',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaija, Lauri',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53571',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaija, Lauri',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/53572',
    'label': 'Ukonmäki',
    'typeLabel': 'M',
    'broaderAreaLabel': 'Antrea',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tuntematon',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/58610',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Anttola',
    'source': 'DNA',
    'lat': '61.553357628163994',
    'long': '27.720984934779',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Taimela-Helenius, Leena',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/58611',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Anttola',
    'source': 'DNA',
    'lat': '61.54979735024',
    'long': '27.713862772333',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Ryynänen, Pirjo',
    'collectionYear': '1970'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/58612',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Anttola',
    'source': 'DNA',
    'lat': '61.609303363466',
    'long': '27.812245408037',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Palosaari, Leena',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/83167',
    'label': 'Ukonmäki',
    'typeLabel': 'Kallio',
    'broaderAreaLabel': 'Aura',
    'source': 'DNA',
    'lat': '60.661016828104',
    'long': '22.600052508943',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Numminen, Esko',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/151679',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Halikko',
    'source': 'DNA',
    'lat': '60.395543674067',
    'long': '22.954924134432996',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lehtolaakso, Leena',
    'collectionYear': '1977'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/157504',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Hankasalmi',
    'source': 'DNA',
    'lat': '62.34759027705999',
    'long': '26.382591289022997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Närhi, Eeva Maria',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/182238',
    'label': 'Ukonmäki',
    'typeLabel': 'Rinne',
    'broaderAreaLabel': 'Haukipudas',
    'source': 'DNA',
    'lat': '65.071898912874',
    'long': '25.416492183483',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Toropainen, Ritva',
    'collectionYear': '1971'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/213710',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Hiitola',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Parkkali, Helmi',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2325106',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Hiitola',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lankinen, Inkeri',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/246342',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Hyrynsalmi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Väyrynen, Tuula',
    'collectionYear': '1978'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/246343',
    'label': 'Ukonmäki',
    'typeLabel': 'Vaara',
    'broaderAreaLabel': 'Hyrynsalmi',
    'source': 'DNA',
    'lat': '64.559968970756',
    'long': '28.696257437435',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Väyrynen, Tuula',
    'collectionYear': '1978'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/246344',
    'label': 'Ukonmäki',
    'typeLabel': 'Rinne',
    'broaderAreaLabel': 'Hyrynsalmi',
    'source': 'DNA',
    'lat': '64.714505291077',
    'long': '28.663837780231',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kemppainen, Tuula',
    'collectionYear': '1976'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/273275',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Iisalmi',
    'source': 'DNA',
    'lat': '63.60432799236',
    'long': '27.034357677425',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Remes, Mauno',
    'collectionYear': '1949'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/273276',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Iisalmi',
    'source': 'DNA',
    'lat': '63.601728112816',
    'long': '26.848378067287',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Remes, Mauno',
    'collectionYear': '1949'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/273277',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Iisalmi',
    'source': 'DNA',
    'lat': '63.606231010767004',
    'long': '26.971590503409',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kauttu, Soili',
    'collectionYear': '1987'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/273278',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Iisalmi',
    'source': 'DNA',
    'lat': '63.46598816579701',
    'long': '27.058200396212',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Remes, Mauno',
    'collectionYear': '1953'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/273279',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Iisalmi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Remes, Mauno',
    'collectionYear': '1953'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/313069',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Imatra',
    'source': 'DNA',
    'lat': '61.23819201646',
    'long': '28.883861014038',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kontiola, Anna-Liisa',
    'collectionYear': '1958'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2330114',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Impilahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lemetyinen, Mandi',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/319001',
    'label': 'Ukonmäki',
    'typeLabel': 'Vaara',
    'broaderAreaLabel': 'Impilahti',
    'source': 'DNA',
    'lat': '61.678434351205',
    'long': '31.412490340917',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hilevaara, Ritva',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/319002',
    'label': 'Ukonmäki',
    'typeLabel': 'Avokallio',
    'broaderAreaLabel': 'Impilahti',
    'source': 'DNA',
    'lat': '61.625533909716',
    'long': '31.374277938987998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hilevaara, Ritva',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2332603',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lätti, Matti',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2332604',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Puhakainen, Elina',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2332605',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lätti, Einar',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2332606',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lätti, Einar',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/342306',
    'label': 'Ukonmäki',
    'typeLabel': 'Kylänosa',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nevalainen, Pirkko',
    'collectionYear': '1971'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/342307',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Penttinen, Eira',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/342308',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Penttinen, Eira',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/342309',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Penttinen, Eira',
    'collectionYear': '1970'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/342310',
    'label': 'Ukonmäki',
    'typeLabel': 'Kennäs',
    'broaderAreaLabel': 'Jaakkima',
    'source': 'DNA',
    'lat': '61.521412927609994',
    'long': '30.379742597111',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Penttinen, Eira',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2044821',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Joutseno',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Viskari, Tanja',
    'collectionYear': '2012'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/416710',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jyväskylä',
    'source': 'DNA',
    'lat': '62.243179049531',
    'long': '25.994982506066',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Berg, Tuija',
    'collectionYear': '1980'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/435182',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jääski',
    'source': 'DNA',
    'lat': '61.024972531632',
    'long': '29.044733550165',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hämäläinen, Eila',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/435183',
    'label': 'Ukonmäki',
    'typeLabel': 'Kallio',
    'broaderAreaLabel': 'Jääski',
    'source': 'DNA',
    'lat': '61.066965398969',
    'long': '29.003031668046',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Toiviainen, Liisa',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/435184',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäet',
    'broaderAreaLabel': 'Jääski',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hämäläinen, Olavi',
    'collectionYear': '1992'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/435185',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jääski',
    'source': 'DNA',
    'lat': '61.024961325595996',
    'long': '29.044749770789',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lehikoinen, Laila',
    'collectionYear': '1969'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/435186',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Jääski',
    'source': 'DNA',
    'lat': '61.024952535718',
    'long': '29.044674585085',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Toiviainen, Liisa',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/441770',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kaavi',
    'source': 'DNA',
    'lat': '62.94590506732099',
    'long': '28.542101061870998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Huuskonen, Matti',
    'collectionYear': '1986'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/441771',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kaavi',
    'source': 'DNA',
    'lat': '63.032106363669996',
    'long': '28.603439385532997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nevalainen, Satu',
    'collectionYear': '1991'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/441772',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kaavi',
    'source': 'DNA',
    'lat': '63.037960685751',
    'long': '28.606188941766',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Evijärvi, Irja-Leena',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/465850',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Kangasala',
    'source': 'DNA',
    'lat': '61.438152256146005',
    'long': '24.269524257694002',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Uotila-Falck, Kirsti',
    'collectionYear': '2000'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/465851',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Kangasala',
    'source': 'DNA',
    'lat': '61.438259402325',
    'long': '24.268381115461',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Suhonen, Riitta',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/478596',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Kangasniemi',
    'source': 'DNA',
    'lat': '61.965155420849',
    'long': '26.723786360669',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tuores, Soile',
    'collectionYear': '1979'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/478597',
    'label': 'Ukonmäki',
    'typeLabel': 'Itärinne',
    'broaderAreaLabel': 'Kangasniemi',
    'source': 'DNA',
    'lat': '61.964991799529',
    'long': '26.821790469992',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Simonen, Katri',
    'collectionYear': '1978'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/514599',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Karttula',
    'source': 'DNA',
    'lat': '62.85453430606999',
    'long': '27.120869186478',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Raatikainen, Ilona',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/514600',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Karttula',
    'source': 'DNA',
    'lat': '62.69456378664',
    'long': '27.298733169838',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Raunio, Olli',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/514601',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Karttula',
    'source': 'DNA',
    'lat': '62.979519361909',
    'long': '27.118974297119003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Raatikainen, Ilona',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/530854',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kauhava',
    'source': 'DNA',
    'lat': '63.166375310033',
    'long': '23.019794835156997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hosiaisluoma, Alli',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/530855',
    'label': 'Ukonmäki',
    'typeLabel': 'Metsä',
    'broaderAreaLabel': 'Kauhava',
    'source': 'DNA',
    'lat': '63.169398773014',
    'long': '23.018011018061',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hosiaisluoma, Alli',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/536133',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kaukola',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Väkevä, Marja-Leena',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/575522',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäkialue',
    'broaderAreaLabel': 'Kerimäki',
    'source': 'DNA',
    'lat': '62.035429124330996',
    'long': '29.553893419227',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Laitinen, Sirkka',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/575523',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Kerimäki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Turtiainen, Aino',
    'collectionYear': '1985'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/575524',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kerimäki',
    'source': 'DNA',
    'lat': '62.024249114304',
    'long': '29.524491402299',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Turtiainen, Aino',
    'collectionYear': '1985'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/575525',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kerimäki',
    'source': 'DNA',
    'lat': '62.034264868324',
    'long': '29.547867002407997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Yli-Paavola, Jaakko',
    'collectionYear': '1975'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/575526',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kerimäki',
    'source': 'DNA',
    'lat': '62.003941182432',
    'long': '28.931552753295',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Pulkkinen, Eija',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/585458',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Kesälahti',
    'source': 'DNA',
    'lat': '62.060802952497994',
    'long': '29.569223223269',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Yli-Paavola, Jaakko',
    'collectionYear': '1975'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/585459',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäkialue',
    'broaderAreaLabel': 'Kesälahti',
    'source': 'DNA',
    'lat': '62.035403006406',
    'long': '29.553959649802',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Laitinen, Sirkka',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/585460',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kesälahti',
    'source': 'DNA',
    'lat': '61.882808599911',
    'long': '29.738887130871',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Surakka, Jouni',
    'collectionYear': '1982'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/585461',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Kesälahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Surakka, Jouni',
    'collectionYear': '1982'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2344409',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kuisma, Erkki',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2344410',
    'label': 'Ukonmäki',
    'typeLabel': 'Vuori',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Näränen, U. A.',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2344411',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Karjalainen, Anna',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2344412',
    'label': 'Ukonmäki',
    'typeLabel': 'Kallio',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leporanta, K.',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2344413',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Arminen, Toimi',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619610',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Räikkönen, Aili',
    'collectionYear': '1958'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619611',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaija, Lauri',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619612',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hämäläinen, Eila',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619613',
    'label': 'Ukonmäki',
    'typeLabel': 'M',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hämäläinen, Eila',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619614',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaija, Lauri',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619615',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lehikoinen, Laila',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619616',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaija, Lauri',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619617',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Ylikuunun nuorisoseura',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619618',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'lat': '61.180971143623',
    'long': '29.271364824608998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hämäläinen, Eila',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619619',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hämäläinen, Eila',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619620',
    'label': 'Ukonmäki',
    'typeLabel': 'Kallio',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hämäläinen, Eila',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/619621',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kirvu',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaija, Lauri',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/634695',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kitee',
    'source': 'DNA',
    'lat': '61.952890564126996',
    'long': '30.077283124031002',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heiskari, Sirkka',
    'collectionYear': '1985'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/634696',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kitee',
    'source': 'DNA',
    'lat': '62.181899792919',
    'long': '29.933524359987',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heiskari, Sirkka',
    'collectionYear': '1980'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/634697',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kitee',
    'source': 'DNA',
    'lat': '62.071853212368005',
    'long': '30.220755486972',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Martiskainen, Briitta',
    'collectionYear': '1973'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/658596',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kiuruvesi',
    'source': 'DNA',
    'lat': '63.898700062996',
    'long': '26.664092167099',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leskinen, Sirkka-Liisa',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/658597',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kiuruvesi',
    'source': 'DNA',
    'lat': '63.845110154744994',
    'long': '26.322372653673',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Martta',
    'collectionYear': '1969'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/658598',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Kiuruvesi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Martta',
    'collectionYear': '1969'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/658599',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kiuruvesi',
    'source': 'DNA',
    'lat': '63.802147380967',
    'long': '26.441500304492997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Martta',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/683920',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Koivisto',
    'source': 'DNA',
    'lat': '60.326600847082005',
    'long': '28.521880007747',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tuuli, Auvo ym.',
    'collectionYear': '2001'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/696829',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Konnevesi',
    'source': 'DNA',
    'lat': '62.581819246911',
    'long': '26.33076029532',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Rossi, Risto',
    'collectionYear': '2009'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/696830',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Konnevesi',
    'source': 'DNA',
    'lat': '62.578443917641',
    'long': '26.330570967633',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Noponen, Irma',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/696831',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Konnevesi',
    'source': 'DNA',
    'lat': '62.713603701241',
    'long': '26.426417441273998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Noponen, Irma',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2360970',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Kurkijoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Immonen, Toivo',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2360971',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kurkijoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tolkki, Eino',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/787547',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kurkijoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Parkkali, Helmi',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/787548',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kurkijoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kiiski, Vappu',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/787550',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kurkijoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kiiski, Vappu',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/787551',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kurkijoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Parkkali, Helmi',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/787552',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Kurkijoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Parkkali, Helmi',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/850621',
    'label': 'Ukonmäki',
    'typeLabel': 'Pelto',
    'broaderAreaLabel': 'Kälviä',
    'source': 'DNA',
    'lat': '63.836328129688994',
    'long': '23.503555380576',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Rytikangas, Ritva',
    'collectionYear': '1953'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069470',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '61.001766817038',
    'long': '28.281463799611',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaipiainen, Lea',
    'collectionYear': '1975'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069471',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '60.896641568514994',
    'long': '28.356128009573997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leinonen, Irja',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069472',
    'label': 'Ukonmäki',
    'typeLabel': 'Mökki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '60.869304191249',
    'long': '28.272498612324',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leinonen, Irja',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069473',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '60.869304191249',
    'long': '28.272498612324',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leinonen, Irja',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069474',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '61.001878059400994',
    'long': '28.278330998753',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Puustinen, Hannele',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069475',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '61.107597286322004',
    'long': '28.348889937237',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Puustinen, Hannele',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069476',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '61.090478698631',
    'long': '28.328980608551998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Paronen, Meri',
    'collectionYear': '2013'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2069477',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lappee',
    'source': 'DNA',
    'lat': '61.037298699263',
    'long': '28.228973332209996',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Väkevä, Marja-Leena',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2363964',
    'label': 'Ukonmäki',
    'typeLabel': 'Hakamaa',
    'broaderAreaLabel': 'Laukaa',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Helminen, Helmi',
    'collectionYear': '1945'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/920772',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Lehtimäki',
    'source': 'DNA',
    'lat': '62.840227084709994',
    'long': '23.974611439788',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Höri, Saara',
    'collectionYear': '1954'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/928064',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lemi',
    'source': 'DNA',
    'lat': '61.049583132747',
    'long': '27.723809101159',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Aurimaa, Sinikka',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/928065',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lemi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kiiski, Marjatta',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/928066',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Lemi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kiiski, Marjatta',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/934938',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Leppävirta',
    'source': 'DNA',
    'lat': '62.518039296919',
    'long': '28.326682789449002',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Koponen, Anneli',
    'collectionYear': '1990'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2368355',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kuntsi, Pekka',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2368356',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Mykkänen, Johannes',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2368357',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaikko, Joh.',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/989951',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Härkönen, Pekka',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/989952',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'lat': '61.357823347632',
    'long': '30.155878206391',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Mikkonen, Pirjo',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/989953',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'lat': '61.357823347632',
    'long': '30.155878206391',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tolkki, Leena',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/989954',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'lat': '61.415233627527996',
    'long': '30.169888045763003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tolkki, Leena',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/989955',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'lat': '61.411643113616',
    'long': '30.174870468666',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Penttinen, Eira',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/989958',
    'label': 'Ukonmäki',
    'typeLabel': 'Kalliomäki',
    'broaderAreaLabel': 'Lumivaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Härkönen, Pekka',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1011919',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Längelmäki',
    'source': 'DNA',
    'lat': '61.729274546277',
    'long': '24.655967195097',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Vesterinen, Arja',
    'collectionYear': '1969'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1039078',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Miehikkälä',
    'source': 'DNA',
    'lat': '60.653679133752',
    'long': '27.897279446412',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Laitinen, Sirkka',
    'collectionYear': '1977'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1039079',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Miehikkälä',
    'source': 'DNA',
    'lat': '60.696554469946',
    'long': '27.532427062209997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Laitinen, Sirkka',
    'collectionYear': '1977'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1039080',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Miehikkälä',
    'source': 'DNA',
    'lat': '60.65498333736301',
    'long': '27.896418218715',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Mattinen, Eija',
    'collectionYear': '1958'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1059562',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Mouhijärvi',
    'source': 'DNA',
    'lat': '61.586046876023',
    'long': '23.060499028998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hartamaa, Marjatta',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1077190',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Muuruvesi',
    'source': 'DNA',
    'lat': '63.065731637652',
    'long': '28.292200603367',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Parviainen, Elsa',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1077191',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Muuruvesi',
    'source': 'DNA',
    'lat': '63.044021206903',
    'long': '28.245461459084',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hanka, Kaija',
    'collectionYear': '1972'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1083154',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Myrskylä',
    'source': 'DNA',
    'lat': '60.591396365824004',
    'long': '25.813772967477004',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lilja, Tuulikki',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1097579',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nastola',
    'source': 'DNA',
    'lat': '61.000468215697005',
    'long': '26.009584254551',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Luoto, Terttu',
    'collectionYear': '1972'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1097580',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nastola',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Rajala, Toivo',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1105489',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nilsiä',
    'source': 'DNA',
    'lat': '63.225388449455004',
    'long': '28.272961761998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Vartiainen, Pentti',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1105490',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nilsiä',
    'source': 'DNA',
    'lat': '63.231545914257005',
    'long': '28.269480919240003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Vartiainen, Pentti',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1105491',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Nilsiä',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Vartiainen, Pentti',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2120721',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nuijamaa',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Patjas, Aune',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2120722',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nuijamaa',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nikku, Kirsti',
    'collectionYear': '1972'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2120723',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nuijamaa',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kuokka, Pirkko',
    'collectionYear': '1955'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2120724',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nuijamaa',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Jäppinen, Sinikka',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2120725',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nuijamaa',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Eteläkarjalaisten nuorisoseurojen liitto',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1126816',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Nurmes',
    'source': 'DNA',
    'lat': '63.466022862631',
    'long': '29.464160386268002',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tuisku, Leena',
    'collectionYear': '1956'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1134813',
    'label': 'Ukonmäki',
    'typeLabel': 'Kallio',
    'broaderAreaLabel': 'Nurmo',
    'source': 'DNA',
    'lat': '62.867822705413',
    'long': '22.878806077328',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heikkinen, Jarmo',
    'collectionYear': '1971'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1134814',
    'label': 'Ukonmäki',
    'typeLabel': 'Metsä',
    'broaderAreaLabel': 'Nurmo',
    'source': 'DNA',
    'lat': '62.866154745657994',
    'long': '22.887632130222997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Salo, Eeva-Kaisa',
    'collectionYear': '1957'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2127954',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Orimattila',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Mattilainen, Sirkka',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2127955',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Orimattila',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Niklander, Outi',
    'collectionYear': '1984'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1172018',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Padasjoki',
    'source': 'DNA',
    'lat': '61.299559121555994',
    'long': '25.088167897957',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kilpi, Topias',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1172019',
    'label': 'Ukonmäki',
    'typeLabel': 'Kahvilarakennus',
    'broaderAreaLabel': 'Padasjoki',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kilpi, Topias',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1192929',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Parikkala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Jantunen, Oiva',
    'collectionYear': '1995'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1192930',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Parikkala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leskinen, Heikki',
    'collectionYear': '1954'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1192931',
    'label': 'Ukonmäki',
    'typeLabel': 'Leikkipaikka',
    'broaderAreaLabel': 'Parikkala',
    'source': 'DNA',
    'lat': '61.567824741867',
    'long': '29.64169509088',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leskinen, Heikki',
    'collectionYear': '1953'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1192932',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Parikkala',
    'source': 'DNA',
    'lat': '61.568013834647',
    'long': '29.640563545313',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Soikkeli, Kaija',
    'collectionYear': '1993'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1243633',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Pieksämäki',
    'source': 'DNA',
    'lat': '62.325246891450995',
    'long': '27.244279448165003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Reinikainen, Kaija',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1243634',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Pieksämäki',
    'source': 'DNA',
    'lat': '62.380219696066',
    'long': '26.882415926451',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Rissanen, Mauno',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1250331',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Pielavesi',
    'source': 'DNA',
    'lat': '63.413090150852',
    'long': '26.919909258251',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kauhanen, Ulla',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1280343',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Pihtipudas',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Pärkkä, Tellervo',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1284184',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Piippola',
    'source': 'DNA',
    'lat': '64.20775921581',
    'long': '26.039026798378',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leskinen, Sirkka-Liisa',
    'collectionYear': '1970'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1338772',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Puumala',
    'source': 'DNA',
    'lat': '61.519785367225',
    'long': '28.528244144534',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hulkkonen, Jaana',
    'collectionYear': '1980'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1352389',
    'label': 'Ukonmäki',
    'typeLabel': 'Mökki',
    'broaderAreaLabel': 'Pyhäjärvi Ol.',
    'source': 'DNA',
    'lat': '63.65324673411801',
    'long': '25.966102218539',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Laiho, Ulla Helena',
    'collectionYear': '1973'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1363733',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Pyhäjärvi Vpl',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Wiika, Impi',
    'collectionYear': '1948'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1363734',
    'label': 'Ukonmäki',
    'typeLabel': 'Ranta',
    'broaderAreaLabel': 'Pyhäjärvi Vpl',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Rautiainen, Juho',
    'collectionYear': '1948'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1363735',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Pyhäjärvi Vpl',
    'source': 'DNA',
    'lat': '60.760139235949',
    'long': '30.491863899304',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Paju, Tuovi',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1379809',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Pyhäselkä',
    'source': 'DNA',
    'lat': '62.441498659699',
    'long': '29.974118153948',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hirvonen, Tauno',
    'collectionYear': '1975'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1417649',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautalampi',
    'source': 'DNA',
    'lat': '62.759515518518',
    'long': '26.654346151664',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Erämetsä, Elvi',
    'collectionYear': '1949'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1426105',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautavaara',
    'source': 'DNA',
    'lat': '63.409740837714004',
    'long': '28.219872634772',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1982'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1426106',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautavaara',
    'source': 'DNA',
    'lat': '63.593619142293996',
    'long': '28.457204924713',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1426107',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Rautavaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1426108',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Rautavaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1426109',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Rautavaara',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182493',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182494',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182495',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182496',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182497',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182498',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182499',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Luumi, Leena',
    'collectionYear': '1983'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182500',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2182501',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rautjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Munnukka, Elli Anneli',
    'collectionYear': '1961'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1445534',
    'label': 'Ukonmäki',
    'typeLabel': 'Kallio',
    'broaderAreaLabel': 'Ristiina',
    'source': 'DNA',
    'lat': '61.492010469991996',
    'long': '27.344101731964997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nevalainen, Pirkko',
    'collectionYear': '1996'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1445535',
    'label': 'Ukonmäki',
    'typeLabel': 'Töyränne',
    'broaderAreaLabel': 'Ristiina',
    'source': 'DNA',
    'lat': '61.419683148431',
    'long': '27.364217898737003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Laalo, Klaus',
    'collectionYear': '1991'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2194335',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Ruokolahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Leskinen, Raili',
    'collectionYear': '1974'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2194336',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Ruokolahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lakkala, Kyllikki',
    'collectionYear': '1960'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2194337',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Ruokolahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Karppinen, Kyllikki',
    'collectionYear': '1951'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2194338',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Ruokolahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Karppinen, Kyllikki',
    'collectionYear': '1950'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2194339',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Ruokolahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Karppinen, Kyllikki',
    'collectionYear': '1952'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1505748',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Rääkkylä',
    'source': 'DNA',
    'lat': '62.348809821935994',
    'long': '29.809639159943',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heiskari, Sirkka',
    'collectionYear': '1979'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1508689',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Saari',
    'source': 'DNA',
    'lat': '61.665324076491004',
    'long': '29.668829168905',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Laitinen, Sirkka',
    'collectionYear': '1978'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1552067',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Savitaipale',
    'source': 'DNA',
    'lat': '61.056907339151',
    'long': '27.477175124612998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaipiainen, Lea',
    'collectionYear': '1972'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1552068',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Savitaipale',
    'source': 'DNA',
    'lat': '61.184958352859',
    'long': '27.744662305194996',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Ikonen, Anna-Liisa',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1576912',
    'label': 'Ukonmäki',
    'typeLabel': 'Mökki',
    'broaderAreaLabel': 'Siilinjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Väänänen, Vilma',
    'collectionYear': '1953'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1576913',
    'label': 'Ukonmäki',
    'typeLabel': 'Työmiesasunto',
    'broaderAreaLabel': 'Siilinjärvi',
    'source': 'DNA',
    'lat': '63.036174371438996',
    'long': '27.604847691566',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Panhelainen, Irmeli',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1576914',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Siilinjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Paldanius, Marja',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1587972',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sippola',
    'source': 'DNA',
    'lat': '60.856518024688995',
    'long': '27.297039446278',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Pitkänen, Ritva Liisa',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1607142',
    'label': 'Ukonmäki',
    'typeLabel': 'Kangas',
    'broaderAreaLabel': 'Soini',
    'source': 'DNA',
    'lat': '62.856127659834996',
    'long': '24.163391614675003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Korhonen, Ritva',
    'collectionYear': '1976'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638977',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'lat': '63.58150935574',
    'long': '27.650981675849',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1980'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638978',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'lat': '63.704981907623996',
    'long': '28.017863862549',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1980'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638979',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'lat': '63.644942966209',
    'long': '27.490981526587',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1978'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638980',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'lat': '63.572628793482',
    'long': '27.630648521335',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1977'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638981',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1977'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638982',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kumpulainen, Matti',
    'collectionYear': '1977'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638983',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'lat': '63.648536183258',
    'long': '27.491848563534003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Moilanen, Reino',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638984',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Moilanen, Reino',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1638985',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sonkajärvi',
    'source': 'DNA',
    'lat': '63.721441274635',
    'long': '27.274630676851',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kääriäinen, Kyllikki',
    'collectionYear': '1954'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1642623',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sortavala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lambert, Janne ym.',
    'collectionYear': '2006'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2397683',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sortavala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Pelkonen, Paavo',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2397684',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Sortavala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Huolman, Juho',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1663529',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Suistamo',
    'source': 'DNA',
    'lat': '61.871934258688',
    'long': '31.044686773211',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tsokkinen, Anja',
    'collectionYear': '1970'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1663530',
    'label': 'Ukonmäki',
    'typeLabel': 'M',
    'broaderAreaLabel': 'Suistamo',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Vuorinen, Lyyli',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1663531',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Suistamo',
    'source': 'DNA',
    'lat': '61.968036082922',
    'long': '31.067202942823',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Rajamo, Mikael',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1663532',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Suistamo',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Rajamo, Mikael',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1663533',
    'label': 'Ukonmäki',
    'typeLabel': 'Korkea maa',
    'broaderAreaLabel': 'Suistamo',
    'source': 'DNA',
    'lat': '61.960248810074',
    'long': '31.104494275911',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tiittanen, Antti',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1663534',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Suistamo',
    'source': 'DNA',
    'lat': '61.957665186933',
    'long': '31.101462763467',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tiittanen, Juho',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1675366',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sumiainen',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Soukka, Matti',
    'collectionYear': '1981'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1705127',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Suomussalmi',
    'source': 'DNA',
    'lat': '65.159626694609',
    'long': '29.084547847108002',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Räisänen, Alpo',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1749660',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sääminki',
    'source': 'DNA',
    'lat': '61.947073315505',
    'long': '28.883817243545',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Vasara, Marjatta',
    'collectionYear': '1974'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1749661',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Sääminki',
    'source': 'DNA',
    'lat': '61.946068629608',
    'long': '28.892508935924',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Turunen, Maini',
    'collectionYear': '1987'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1756206',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Taipalsaari',
    'source': 'DNA',
    'lat': '61.167685011485005',
    'long': '28.129365241332998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Oksman, Pertti',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1756207',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Taipalsaari',
    'source': 'DNA',
    'lat': '61.238409513927',
    'long': '28.054671975441998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tiainen, Marja',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1794481',
    'label': 'Ukonmäki',
    'typeLabel': 'Tila',
    'broaderAreaLabel': 'Tervo',
    'source': 'DNA',
    'lat': '62.967444770674',
    'long': '26.812321397582',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tolonen, Eila',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1794482',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Tervo',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tolonen, Eila',
    'collectionYear': '1966'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1886639',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vahviala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Pusa, Liisi',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1886640',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vahviala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Koskelainen, Kerttu',
    'collectionYear': '1948'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1886641',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vahviala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Noponen, Aila',
    'collectionYear': '1969'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1886642',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vahviala',
    'source': 'DNA',
    'lat': '60.774411702299005',
    'long': '28.436951438846997',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nuutinen, Olavi',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1886643',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vahviala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Sipiläinen, Armas',
    'collectionYear': '1948'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2413579',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vahviala',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tetri, Laura',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1930167',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Varpaisjärvi',
    'source': 'DNA',
    'lat': '63.505074984372996',
    'long': '27.720644498730998',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kinnunen, Pirjetta',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1930168',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Varpaisjärvi',
    'source': 'DNA',
    'lat': '63.386324051819',
    'long': '27.945579451711',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heikkilä, Ulla',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1930169',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Varpaisjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heikkilä, Ulla',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1930170',
    'label': 'Ukonmäki',
    'typeLabel': 'Undefined',
    'broaderAreaLabel': 'Varpaisjärvi',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heikkilä, Ulla',
    'collectionYear': '1968'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1936661',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vehkalahti',
    'source': 'DNA',
    'lat': '60.720506492557',
    'long': '27.207579790092',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lanki, Raija',
    'collectionYear': '1964'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2421691',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vieremä',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Remes, Mauno',
    'collectionYear': '1948'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1982586',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Viipuri',
    'source': 'DNA',
    'lat': '60.605632218286',
    'long': '28.809627209577',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Lauhio, Mirja',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1982587',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Viipuri',
    'source': 'DNA',
    'lat': '60.800375673854',
    'long': '28.790375736484',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Ylén-Julin, Leena',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1982588',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Viipuri',
    'source': 'DNA',
    'lat': '60.733926515528005',
    'long': '28.869811096321996',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Karvinen, Ismo',
    'collectionYear': '1962'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2423874',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Viipuri',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hakkarainen, Samuel',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2423875',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Viipuri',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hakkarainen, Samuel',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1988573',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Viitasaari',
    'source': 'DNA',
    'lat': '63.112393063535',
    'long': '25.809715120788002',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Saraste, Martti',
    'collectionYear': '1951'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1996946',
    'label': 'Ukonmäki',
    'typeLabel': 'M',
    'broaderAreaLabel': 'Virolahti',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Pohjola, Eino',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2257190',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Virrat',
    'source': 'DNA',
    'lat': '62.129363311115',
    'long': '23.833651356411',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Jussila, Kirsti',
    'collectionYear': '1967'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/1998629',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Ruponen, Tyyni',
    'collectionYear': '1963'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2430910',
    'label': 'Ukonmäki',
    'typeLabel': 'M',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Sokka, Antti',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2430911',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Sokka, Antti',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2430912',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1934'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2430913',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Nissilä, Viljo',
    'collectionYear': '1934'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2430914',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Heikkonen, Elvi',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2430915',
    'label': 'Ukonmäki',
    'typeLabel': 'Talo',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Meronen, Hilkka',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2430916',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Vuoksenranta',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Meronen, Hilkka',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2269691',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Ylikiiminki',
    'source': 'DNA',
    'lat': '65.036807885913',
    'long': '26.031062837466003',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kylmänen, Liisa',
    'collectionYear': '1958'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2312131',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Äyräpää',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Soila, Evi',
    'collectionYear': '1948'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2312132',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Äyräpää',
    'source': 'DNA',
    'lat': '60.69256263297',
    'long': '29.42044742967',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Tiainen, Marja',
    'collectionYear': '1965'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2312133',
    'label': 'Ukonmäki',
    'typeLabel': 'Kumpu',
    'broaderAreaLabel': 'Äyräpää',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Mäkelä, Lauri',
    'collectionYear': '1959'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2433846',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Äyräpää',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Hätönen, Väinö',
    'collectionYear': '1941'
  },
  {
    's': 'http://ldf.fi/kotus-digital-names-archive/2433847',
    'label': 'Ukonmäki',
    'typeLabel': 'Mäki',
    'broaderAreaLabel': 'Äyräpää',
    'source': 'DNA',
    'modifier': 'Ukon',
    'basicElement': 'Mäki',
    'collector': 'Kaukinen, Matti',
    'collectionYear': '1941'
  }
];
