import {
  UPDATE_QUERY,
  UPDATE_DATASETS,
  UPDATE_SUGGESTIONS,
  CLEAR_SUGGESTIONS,
  UPDATE_RESULTS,
  CLEAR_RESULTS
} from '../actions';
import suggestions from './suggestions';
import results from './results';

export const INITIAL_STATE = {
  query: 'kive',
  datasets: ['warsa_karelian_places', 'warsa_municipalities'],
  suggestions: [],
  results: [ { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_20949',
    label: 'Kiveksienkennäs',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Lumivaara',
    lat: '61.470031',
    long: '30.12829',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_19450',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Jääski',
    lat: '60.998066',
    long: '28.795745',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_26729',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Uukuniemi',
    lat: '61.703397',
    long: '30.03475',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_31110',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Uukuniemi',
    lat: '61.784059',
    long: '30.167493',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_15730',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Hiitola',
    lat: '61.182671',
    long: '29.736767',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_22715',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Kanneljärvi',
    lat: '60.401013',
    long: '29.452854',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_14516',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Kurkijoki',
    lat: '61.478766',
    long: '29.715502',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_21873',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Käkisalmen mlk',
    lat: '60.958474',
    long: '30.163148',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_26423',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Käkisalmen mlk',
    lat: '61.048316',
    long: '29.99702',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_26573',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Rautu',
    lat: '60.527514',
    long: '30.270254',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_27354',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Räisälä',
    lat: '60.940371',
    long: '29.738772',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_18419',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Suojärvi',
    lat: '62.113113',
    long: '32.410906',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_25949',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Valkjärvi',
    lat: '60.518527',
    long: '29.723975',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_29974',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Viipurin mlk',
    lat: '60.594928',
    long: '28.883801',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_30290',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Viipurin mlk',
    lat: '60.708614',
    long: '28.568478',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_19637',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Viipurin mlk',
    lat: '60.863643',
    long: '28.819216',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_19068',
    label: 'Kivelä',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Vuoksenranta',
    lat: '60.796359',
    long: '29.574668',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_38361',
    label: 'Kivenjoki',
    typeLabel: 'Vesimuodostuma',
    broaderAreaLabel: 'Sortavalan mlk',
    lat: '61.69327',
    long: '30.563798',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_13448',
    label: 'Kivenjuuri',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Kurkijoki',
    lat: '61.407188',
    long: '29.847207',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_28671',
    label: 'Kivenkaivanto',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Lumivaara',
    lat: '61.416124',
    long: '30.184251',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_30183',
    label: 'Kivenkolkka',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Metsäpirtti',
    lat: '60.589715',
    long: '30.489737',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_26220',
    label: 'Kivenkorva',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Kesälahti',
    lat: '61.829013',
    long: '29.939999',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_14191',
    label: 'Kivenkorva',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Antrea',
    lat: '60.875455',
    long: '29.205412',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_30481',
    label: 'Kivenkulma',
    typeLabel: 'Rakennettu kohde',
    broaderAreaLabel: 'Sortavalan mlk',
    lat: '61.710203',
    long: '30.772071',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_38957',
    label: 'Kivenkulmankoski',
    typeLabel: 'Vesimuodostuma',
    broaderAreaLabel: 'Salmi',
    lat: '61.550062',
    long: '31.633363',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_14',
    label: 'Kivennapa',
    typeLabel: 'Kirkonkylä , kaupunki',
    broaderAreaLabel: 'Kivennapa',
    lat: '60.348002',
    long: '29.72542',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_9242',
    label: 'Kivennavanmäki',
    typeLabel: 'Maastokohde',
    broaderAreaLabel: 'Impilahti',
    lat: '61.623947',
    long: '31.448691',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/karelian_places/k_place_10136',
    label: 'Kivennavansaari',
    typeLabel: 'Maastokohde',
    broaderAreaLabel: 'Äyräpää',
    lat: '60.741968',
    long: '29.428721',
    source: 'KMN' },
  { s: 'http://ldf.fi/warsa/places/municipalities/m_place_568',
    label: 'Kivennapa',
    typeLabel: 'Kunta',
    broaderAreaLabel: 'Viipurin lääni',
    lat: '60.365334',
    long: '29.820196',
    source: 'FWM' } ]
};

const search = (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case UPDATE_QUERY:
      return { ...state, query: action.query || '' };
    case UPDATE_DATASETS:
      return { ...state, datasets: action.datasets || [] };
    case CLEAR_SUGGESTIONS:
    case UPDATE_SUGGESTIONS:
      return { ...state, suggestions: suggestions(state.suggestions, action) };
    case CLEAR_RESULTS:
    case UPDATE_RESULTS:
      return {
        ...state,
        suggestions: [],
        results: results(state.results, action)

      };
    default:
      return state;
  }
};

export default search;
